name: Deploy into VM
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        runner: [self-hosted, php-runner]
    steps:   
      - name: Checkout code        
        uses: actions/checkout@v2

      - name: Use PHP 8.2.x
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2.x

      - name: Check if composer.json exists
        id: check_files
        run: test -f composer.json && echo "Found" || echo "Not found"

      - name: Get Composer Cache Directory
        if: steps.check_files.outputs.files_exists == 'Found'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Set up dependency caching for faster installs
        if: steps.check_files.outputs.files_exists == 'Found'
        uses: actions/cache@v2
        with:
          path: ${{ env.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'Found'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Update Composer
        run: composer self-update

      - name: Install Dependencies
        run: composer update

      - name: Install zip
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Zip artifact for deployment
        run: zip -r release.zip *

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: release.zip
          
  deploy:
    runs-on: self-hosted   
    needs: build
    steps: 
      - name: Unzip Files
        run: unzip -o release.zip
      - name: Remove contents of target directory
        run: sudo rm -rf /home/suresh.velpula/target/*

      - name: Check if prod directory exists
        run: |
          if [ -d "/home/suresh.velpula/prod" ]; then
            sudo rm -rf /home/suresh.velpula/prod/*  # Remove files from prod directory if it exists
          else
            echo "Prod directory does not exist."
          fi

      - name: Move files to target and prod directories
        run: |
          sudo mv /home/suresh.velpula/_work/php/* /home/suresh.velpula/target/
          sudo mv /home/suresh.velpula/_work/php/* /home/suresh.velpula/prod/
